version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: recon
      POSTGRES_PASSWORD: recon_password
      POSTGRES_DB: recon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    container_name: celery_worker
    entrypoint: []
    command: celery -A core.tasks worker --loglevel=info --concurrency=10
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://recon:recon_password@db:5432/recon_db
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db
      - recon-framework

  recon-framework:
    build: .
    container_name: recon_framework
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    entrypoint: []
    command: uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://recon:recon_password@db:5432/recon_db
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db

  mock-target:
    build: ./mock_target
    container_name: mock_target
    ports:
      - "5000:5000"

volumes:
  postgres_data:
